name: spring_bottom_sheet_example
description: Example app for the spring_bottom_sheet package.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  spring_bottom_sheet:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
