name: spring_bottom_sheet
description: A lightweight Flutter package that provides a beautiful spring-animated bottom sheet with automatic height adjustment and smooth animations.
version: 0.0.2
homepage: https://github.com/trongnhangle/spring_bottom_sheet
repository: https://github.com/trongnhangle/spring_bottom_sheet
issue_tracker: https://github.com/trongnhangle/spring_bottom_sheet/issues
topics:
  - animation
  - ui
  - bottom_sheet
  - modal
  - spring
  - widget
funding:
  - https://www.paypal.me/trongnhangle

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
